project:
  type: website
  output-dir: _site

website:
  title: "cuda-mppi"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Plans"
        href: plan/index.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
          - intro/getting_started.qmd
      - section: "Core Concepts"
        contents:
          - core/architecture.qmd
          - core/jit.qmd
      - section: "Controllers"
        contents:
          - controllers/controllers.qmd
          - controllers/i_mppi.qmd
      - section: "API Reference"
        contents:
          - api/python_api.qmd
      - section: "Development"
        contents:
          - dev/development.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true